---
title: "COVID Project"
author: "Danielle Sebring"
date: "10/10/2020"
output: pdf_document
---

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
# library(coronavirus)
# # https://cran.r-project.org/web/packages/coronavirus/coronavirus.pdf
# 
# 
# library(utils)
# # https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide


library(RSocrata)
# https://www.vdh.virginia.gov/coronavirus/
```



```{r eval=F}
get_info_coronavirus()

d1 <- data.frame(coronavirus) #COVID around the world
dUS <- subset(d1,country=="US") #COVID in the US

dUSC <- subset(dUS,type=="confirmed") #confirmed cases in the US
dUSD <- subset(dUS,type=="death") #death cases in the US
dUSR <- subset(dUS,type=="recovered") #recovered cases in the US

dUSC$days <- seq(1:nrow(dUSC)) #days since (and including) January 21 2020 (US confirmed)
dUSD$days <- seq(1:nrow(dUSD)) #days since (and including) January 21 2020 (US death)
dUSR$days <- seq(1:nrow(dUSR)) #days since (and including) January 21 2020 (US recovered)

plot(dUSC$days,dUSC$cases) #confirmed cases by days
plot(dUSD$days,dUSD$cases) #death cases by days
plot(dUSR$days,dUSR$cases) #recovered cases by days

plot(d1$lat,d1$long) #could put this over a world map
```



```{r eval=F}
### awesome worldwide case data
WorldData <- read.csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", na.strings = "", fileEncoding = "UTF-8-BOM")
head(data)
```


```{r}
#virginia data -- using API
library(RSocrata)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(janitor)
library(lubridate)
va_bysex <- read.socrata("https://data.virginia.gov/resource/tdt3-q47w.json")
va_byrace <- read.socrata("https://data.virginia.gov/resource/9sba-m86n.json")
va_byage <- read.socrata("https://data.virginia.gov/resource/uktn-mwig.json")


# Clean datasets
va_bysex_clean <- janitor::clean_names(va_bysex) %>% 
  filter(!is.na(health_district), sex != "Not Reported") %>% 
  mutate(demographic = "sex") %>% 
  rename(level = sex)

va_byrace_clean <- janitor::clean_names(va_byrace) %>% 
  filter(!is.na(health_district_or_health), race_and_ethnicity != "Not Reported") %>% 
  mutate(demographic = "race") %>% 
  rename(level = race_and_ethnicity, health_district = health_district_or_health)

va_byage_clean <- janitor::clean_names(va_byage) %>% 
  filter(!is.na(health_district), age_group != "Not Reported") %>% 
  mutate(demographic = "age") %>% 
  rename(level = age_group)


# Keep only data where dates overlap
date_ranges <- intersect(intersect(va_bysex_clean$report_date, va_byrace_clean$report_date),
                         va_byage_clean$report_date)


# Merge sex and race datasets
va_merged <- rbind(va_bysex_clean, va_byrace_clean, va_byage_clean) %>% 
  filter(report_date %in% date_ranges) %>% 
  mutate(date = lubridate::ymd(report_date)) %>% 
  gather(key = "statistic", value = "count", number_of_cases, number_of_hospitalizations, number_of_deaths) %>% 
  mutate(statistic = statistic %>% factor(levels = c("number_of_cases", "number_of_hospitalizations",
                                           "number_of_deaths"),
                                labels = c("cases", "hospitalizations", "deaths")))


va_complete <- va_merged


# Save dataset to be loaded in shiny app
saveRDS(va_complete, "va_covid")


```


```{r}
####### I don't think a mosaic will be useful ##########
library(ggplot2)
library(ggmosaic)
va_data <- readRDS("va_covid")
ggplot(data =  va_data) +
  geom_mosaic(aes(x = product(demographic,level), fill= factor(statistic)), na.rm=TRUE) +
  scale_fill_discrete("")+
  labs(x = "Health District", y = "Demographic", title='')+ theme_bw()
```





